### ISSUE TITLE
Live version of documentation is outdated

### ISSUE THREAD

**Issue by davidkopp** [green-coding-solutions/documentation#72]
The live version of the documentation doesn't include the latest changes. The last build was from commit https://github.com/green-coding-solutions/documentation/commit/2169a3dbad82568187a146a8ee596e941c03606b which is 2 months old

**Comment by ArneTR** [comment]
Thanks for the ping. 

Suprisingly the integration ripped on the docs after we changed from green-coding-berlin to green-coding-solutions but did not so on our main website.

Should all be live now. Please close if all you were looking for is now visible.

Ty!
