### ISSUE TITLE
Repository link points to non-existing domain

### ISSUE THREAD

**Issue by almereyda** [green-coding-solutions/documentation#74]
The repository link that is displayed alongside the overview of the repository links to a non-existing domain.

![grafik](https://github.com/green-coding-solutions/documentation/assets/1645308/01daa4d0-eb71-4315-b5d0-724506f31251)

The "fix" is to replace `.org` with `.io`.

**Comment by ribalba** [comment]
Thank you ever so much for spotting that. Must have been there for ages. Fixed

**Comment by almereyda** [comment]
![grafik](https://github.com/green-coding-solutions/documentation/assets/1645308/1a83c918-e686-404f-ae88-4957741e18e6)

If you'd like to simplify things even further, I think it would be sane to even remove the Denglish formulation (native speakers would probably use "which"):

> that can be found under https://…

and to use lowercase letters for nouns, plus a little specification what the documentation is about, e.g.:

> Source files of the Green Coding documentation

:)
